pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'g++ -o hello Jenkins_lab-main/Jenkinsfile/abc1.cpp'
                build 'PES1UG20CS401-1'
                echo 'Build stage successful'
            }
        }

        stage('Test') {
            steps {
                sh './hello'
                echo 'Test stage successful'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy stage successful'
            }
        }
    }

    post {
        always {
            script {
                if (currentBuild.result == 'FAILURE') {
                    echo 'Pipeline failed'
                }
            }
        }
    }
}
